platform :ios, '15.1'  # Ensure your iOS version is compatible

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

$RNFirebaseAsStaticFramework = true
prepare_react_native_project!
  # Use frameworks for static linkage
use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true
target 'VardhmanKrupa' do
  config = use_native_modules!

  # Configure React Native
  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => false  # Enable Hermes if desired
  )

  

  # Add dependencies for tests
  target 'VardhmanKrupaTests' do
    inherit! :complete
    # Add test-specific pods here
  end

  # Post-install hooks for React Native
  post_install do |installer|
    react_native_post_install(installer)
    # Workaround for Xcode 14+ issues
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
end
